default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] || "56792feef405a59b18ea7db57b4777e855103882b926413d4afdfb8c0ea8aa86ea6649da4e729c5f5ae324c0ab9338f789174cf48c544173bc18fdc3b14262e4" %> 

development:
  <<: *default

test:
  <<: *default

staging:
  server_name: ""
  <<: *default

production: &production
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] || "974db513f94c26a0562e612e2c3687228f40d2be43b85b99379c4d68d7eaa3c3f4e66a19e8fd0c2da791a2750b0a76d68b459f65cc4eb26931de2d7bad9946a2" %> 
  census_api_end_point: ""
  census_api_institution_code: ""
  census_api_portal_name: ""
  census_api_user_code: ""

  sms_end_point:  ""
  sms_username: ""
  sms_password: ""

  http_basic_username: ""
  http_basic_password: ""

  twitter_key: ""
  twitter_secret: ""
  facebook_key: ""
  facebook_secret: ""
  google_oauth2_key: ""
  google_oauth2_secret: ""

  translate_username: ""
  translate_password:  ""

  rollbar_server_token: ""
  server_name: ""

preproduction:
  server_name: ""
  <<: *production
